[package]
name = "xkey-pipe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
x11rb = { version = "0.13.1", features = ["extra-traits", "xtest"] }
